// This is largely AI generated by ChatGPT
// I only modified some stuff here and there

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using UnityEngine;

namespace _Project.Scripts
{
    public class SettingsIMGUI : MonoBehaviour
    {
        [Serializable]
        private class DrawModeText
        {
            public Settings.DrawMode mode;

            [TextArea(3, 8)]
            public string text;
        }

        public Settings settings => Manager.Settings;

        [SerializeField] private List<DrawModeText> drawModeTexts = new();

        private Rect settingsWindowRect = new Rect(20, 20, 360, 650);
        private Rect drawModeTextWindowRect = new Rect(20, 690, 360, 360);

        private Vector2 settingsScroll;

        private readonly Dictionary<string, string> textBuffers = new();
        private readonly HashSet<string> focusedLastFrame = new();

        private GUIStyle windowStyle;
        private GUIStyle labelStyle;
        private GUIStyle headerStyle;
        private GUIStyle toggleStyle;
        private GUIStyle buttonStyle;
        private GUIStyle textFieldStyle;
        private GUIStyle textAreaStyle;
        private GUIStyle selectionButtonStyle;
        private GUIStyle boxStyle;

        private Texture2D windowBackground;
        private Texture2D controlBackground;
        private Texture2D controlHoverBackground;
        private Texture2D controlActiveBackground;

        private const int LabelWidth = 150;
        private const int FontSize = 14;
        private const int HeaderFontSize = 16;

        public string GetDrawModeText(Settings.DrawMode mode)
        {
            EnsureDrawModeTextEntries();

            foreach (DrawModeText entry in drawModeTexts)
            {
                if (entry.mode == mode)
                    return entry.text ?? string.Empty;
            }

            return string.Empty;
        }

        private void OnGUI()
        {
            EnsureStyles();

            Color oldContentColor = GUI.contentColor;
            Color oldBackgroundColor = GUI.backgroundColor;

            GUI.contentColor = Color.white;
            GUI.backgroundColor = new Color(0.35f, 0.35f, 0.35f);

            if (settings == null)
            {
                GUILayout.Box("SettingsIMGUI: No Settings assigned.", boxStyle);
                RestoreGuiColors(oldContentColor, oldBackgroundColor);
                return;
            }

            EnsureDrawModeTextEntries();

            settingsWindowRect = GUI.Window(
                GetInstanceID(),
                settingsWindowRect,
                DrawSettingsWindow,
                "Settings",
                windowStyle
            );

            drawModeTextWindowRect = GUI.Window(
                GetInstanceID() + 1,
                drawModeTextWindowRect,
                DrawDrawModeTextWindow,
                "Info",
                windowStyle
            );

            RestoreGuiColors(oldContentColor, oldBackgroundColor);
        }

        private static void RestoreGuiColors(Color contentColor, Color backgroundColor)
        {
            GUI.contentColor = contentColor;
            GUI.backgroundColor = backgroundColor;
        }

        private void DrawSettingsWindow(int id)
        {
            settingsScroll = GUILayout.BeginScrollView(settingsScroll);

            DrawSimulationSettings();
            DrawDrawSettings();
            DrawFieldSettings();
            DrawElementSettings();

            GUILayout.EndScrollView();

            GUI.DragWindow(new Rect(0, 0, 10000, 24));
        }

        private void DrawDrawModeTextWindow(int id)
        {
            DrawModeText entry = drawModeTexts.Find(e => e.mode == Manager.Settings.drawMode);

            GUILayout.Label(NicifyEnumName(entry.mode.ToString()), headerStyle);

            GUILayout.Label(
                entry.text ?? string.Empty,
                textAreaStyle,
                GUILayout.MinHeight(80),
                GUILayout.ExpandWidth(true)
            );
            
            GUI.DragWindow(new Rect(0, 0, 10000, 24));
        }

        private void DrawSimulationSettings()
        {
            Header("Simulation");

            GUILayout.BeginHorizontal();
            if (GUILayout.Button("Reset", buttonStyle)) Manager.instance.Reset();
            if (GUILayout.Button("Step", buttonStyle)) Manager.instance.Step();
            if (GUILayout.Button("Recenter", buttonStyle)) Manager.instance.Recenter();
            GUILayout.EndHorizontal();
            
            settings.simulate = Toggle("Simulate", settings.simulate);
            settings.nSamples = IntField("Samples", settings.nSamples);
            settings.perplexity = FloatField("Perplexity", settings.perplexity);
            settings.targetRate = FloatField("Target Rate /s", settings.targetRate);
        }

        private void DrawElementSettings()
        {
            Header("Element Settings");
            
            settings.showPoints = Toggle("Show Points", settings.showPoints);
            settings.pointSize = FloatField("Point Size", settings.pointSize);
            settings.arrowSize = FloatField("Arrow Size", settings.arrowSize);
        }

        private void DrawDrawSettings()
        {
            Header("Draw Settings");

            settings.drawMode = EnumField("Draw Mode", settings.drawMode);
        }

        private void DrawFieldSettings()
        {
            Header("Field Settings");

            settings.FieldResolution = FloatField("Field Resolution", settings.FieldResolution);
            settings.KernelResolution = FloatField("Kernel Resolution", settings.KernelResolution);
            settings.KernelSize = Vector2IntField("Kernel Size", settings.KernelSize);
        }

        private void Header(string text)
        {
            GUILayout.Space(10);
            GUILayout.Label(text, headerStyle);
        }

        private bool Toggle(string label, bool value)
        {
            return GUILayout.Toggle(value, label, toggleStyle);
        }

        private int IntField(string label, int value)
        {
            GUILayout.BeginHorizontal();
            GUILayout.Label(label, labelStyle, GUILayout.Width(LabelWidth));

            value = DelayedIntTextField(label, value);

            GUILayout.EndHorizontal();
            return value;
        }

        private float FloatField(string label, float value)
        {
            GUILayout.BeginHorizontal();
            GUILayout.Label(label, labelStyle, GUILayout.Width(LabelWidth));

            value = DelayedFloatTextField(label, value);

            GUILayout.EndHorizontal();
            return value;
        }

        private Vector2Int Vector2IntField(string label, Vector2Int value)
        {
            GUILayout.BeginHorizontal();
            GUILayout.Label(label, labelStyle, GUILayout.Width(LabelWidth));

            value.x = DelayedIntTextField(label + ".x", value.x, GUILayout.Width(80));
            value.y = DelayedIntTextField(label + ".y", value.y, GUILayout.Width(80));

            GUILayout.EndHorizontal();
            return value;
        }

        private int DelayedIntTextField(string key, int value, params GUILayoutOption[] options)
        {
            string text = DelayedTextField(key, value.ToString(CultureInfo.InvariantCulture), options);

            if (ShouldCommit(key) &&
                int.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out int result))
            {
                value = result;
                textBuffers[key] = value.ToString(CultureInfo.InvariantCulture);
            }

            return value;
        }

        private float DelayedFloatTextField(string key, float value, params GUILayoutOption[] options)
        {
            string text = DelayedTextField(key, value.ToString(CultureInfo.InvariantCulture), options);

            if (ShouldCommit(key) &&
                float.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out float result))
            {
                value = result;
                textBuffers[key] = value.ToString(CultureInfo.InvariantCulture);
            }

            return value;
        }

        private string DelayedTextField(string key, string currentValue, params GUILayoutOption[] options)
        {
            bool isFocused = GUI.GetNameOfFocusedControl() == key;

            if (!textBuffers.ContainsKey(key) || !isFocused && !focusedLastFrame.Contains(key))
                textBuffers[key] = currentValue;

            GUI.SetNextControlName(key);
            textBuffers[key] = GUILayout.TextField(textBuffers[key], textFieldStyle, options);

            return textBuffers[key];
        }

        private bool ShouldCommit(string key)
        {
            bool isFocused = GUI.GetNameOfFocusedControl() == key;
            bool wasFocused = focusedLastFrame.Contains(key);

            bool enterPressed =
                isFocused &&
                Event.current.type == EventType.KeyDown &&
                (Event.current.keyCode == KeyCode.Return ||
                 Event.current.keyCode == KeyCode.KeypadEnter);

            bool lostFocus = wasFocused && !isFocused;

            if (enterPressed)
            {
                GUI.FocusControl("");
                Event.current.Use();
            }

            if (isFocused)
                focusedLastFrame.Add(key);
            else
                focusedLastFrame.Remove(key);

            return lostFocus || enterPressed;
        }

        private Settings.DrawMode EnumField(string label, Settings.DrawMode value)
        {
            GUILayout.Label(label, labelStyle);

            string[] names = Enum.GetNames(typeof(Settings.DrawMode)).Select(NicifyEnumName).ToArray();
            int selected = GUILayout.SelectionGrid((int)value, names, 1, selectionButtonStyle);

            return (Settings.DrawMode)selected;
        }

        private void EnsureDrawModeTextEntries()
        {
            foreach (Settings.DrawMode mode in Enum.GetValues(typeof(Settings.DrawMode)))
            {
                bool exists = false;

                foreach (DrawModeText entry in drawModeTexts)
                {
                    if (entry.mode == mode)
                    {
                        exists = true;
                        break;
                    }
                }

                if (!exists)
                {
                    drawModeTexts.Add(new DrawModeText
                    {
                        mode = mode,
                        text = string.Empty
                    });
                }
            }
        }


        private static string NicifyEnumName(string name)
        {
            if (string.IsNullOrEmpty(name))
                return string.Empty;

            string result = name[0].ToString();

            for (int i = 1; i < name.Length; i++)
            {
                char current = name[i];
                char previous = name[i - 1];

                if (char.IsUpper(current) && !char.IsWhiteSpace(previous))
                    result += " ";

                result += current;
            }

            return result;
        }

        private void EnsureStyles()
        {
            if (windowStyle != null)
                return;

            windowBackground = MakeTexture(new Color(0.08f, 0.08f, 0.08f, 0.98f));
            controlBackground = MakeTexture(new Color(0.18f, 0.18f, 0.18f, 1f));
            controlHoverBackground = MakeTexture(new Color(0.26f, 0.26f, 0.26f, 1f));
            controlActiveBackground = MakeTexture(new Color(0.34f, 0.34f, 0.34f, 1f));

            windowStyle = new GUIStyle(GUI.skin.window)
            {
                fontSize = FontSize,
                fontStyle = FontStyle.Bold,
                padding = new RectOffset(12, 12, 26, 12),
                normal =
                {
                    textColor = Color.white,
                    background = windowBackground
                },
                onNormal =
                {
                    textColor = Color.white,
                    background = windowBackground
                }
            };

            labelStyle = new GUIStyle(GUI.skin.label)
            {
                fontSize = FontSize,
                normal =
                {
                    textColor = new Color(0.92f, 0.92f, 0.92f)
                }
            };

            headerStyle = new GUIStyle(GUI.skin.label)
            {
                fontSize = HeaderFontSize,
                fontStyle = FontStyle.Bold,
                normal =
                {
                    textColor = Color.white
                }
            };

            toggleStyle = new GUIStyle(GUI.skin.toggle)
            {
                fontSize = FontSize,
                normal =
                {
                    textColor = new Color(0.92f, 0.92f, 0.92f)
                },
                onNormal =
                {
                    textColor = Color.white
                },
                hover =
                {
                    textColor = Color.white
                },
                onHover =
                {
                    textColor = Color.white
                }
            };

            buttonStyle = new GUIStyle(GUI.skin.button)
            {
                fontSize = FontSize,
                fontStyle = FontStyle.Bold,
                margin = new RectOffset(2, 2, 4, 4),
                padding = new RectOffset(8, 8, 6, 6),
                normal =
                {
                    textColor = Color.white,
                    background = controlBackground
                },
                hover =
                {
                    textColor = Color.white,
                    background = controlHoverBackground
                },
                active =
                {
                    textColor = Color.white,
                    background = controlActiveBackground
                }
            };

            selectionButtonStyle = new GUIStyle(buttonStyle)
            {
                alignment = TextAnchor.MiddleLeft
            };

            textFieldStyle = new GUIStyle(GUI.skin.textField)
            {
                fontSize = FontSize,
                padding = new RectOffset(6, 6, 4, 4),
                normal =
                {
                    textColor = Color.white,
                    background = controlBackground
                },
                focused =
                {
                    textColor = Color.white,
                    background = controlActiveBackground
                },
                hover =
                {
                    textColor = Color.white,
                    background = controlHoverBackground
                }
            };

            textAreaStyle = new GUIStyle(textFieldStyle)
            {
                wordWrap = true,
                stretchHeight = true
            };

            boxStyle = new GUIStyle(GUI.skin.box)
            {
                fontSize = FontSize,
                normal =
                {
                    textColor = Color.white,
                    background = windowBackground
                }
            };
        }

        private static Texture2D MakeTexture(Color color)
        {
            Texture2D texture = new Texture2D(1, 1)
            {
                hideFlags = HideFlags.HideAndDontSave
            };

            texture.SetPixel(0, 0, color);
            texture.Apply();

            return texture;
        }
    }
}
