// This is largely AI generated by ChatGPT
// I only modified some stuff here and there

using System;
using System.Collections.Generic;
using System.Globalization;
using UnityEngine;

namespace _Project.Scripts
{
    public class SettingsIMGUI : MonoBehaviour
    {
        public Settings settings => Manager.Settings;

        private Rect windowRect = new Rect(20, 20, 320, 600);
        private Vector2 scroll;
        
        private readonly Dictionary<string, string> textBuffers = new();
        private readonly HashSet<string> focusedLastFrame = new();

        private void OnGUI()
        {
            if (settings == null)
            {
                GUILayout.Box("SettingsIMGUI: No Settings assigned.");
                return;
            }

            windowRect = GUI.Window(
                GetInstanceID(),
                windowRect,
                DrawWindow,
                "Settings"
            );
        }

        private void DrawWindow(int id)
        {
            scroll = GUILayout.BeginScrollView(scroll);

            DrawSimulationSettings();
            DrawPointSettings();
            DrawDrawSettings();
            DrawFieldSettings();
            DrawArrowSettings();

            GUILayout.EndScrollView();

            GUI.DragWindow();
        }
        
        private void DrawSimulationSettings()
        {
            Header("Simulation");

            if (GUILayout.Button("Reset")) Manager.instance.Reset();
            if (GUILayout.Button("Step")) Manager.instance.Step();
            if (GUILayout.Button("Recenter")) Manager.instance.Recenter();
            settings.simulate = Toggle("Simulate", settings.simulate);
            settings.perplexity = FloatField("Perplexity", settings.perplexity);
            settings.targetRate = FloatField("Target Rate /s", settings.targetRate);
        }

        private void DrawPointSettings()
        {
            Header("Point Settings");

            settings.nSamples = IntField("Samples", settings.nSamples);
            settings.showPoints = Toggle("Show Points", settings.showPoints);
            settings.pointSize = FloatField("Point Size", settings.pointSize);
        }

        private void DrawDrawSettings()
        {
            Header("Draw Settings");

            settings.drawMode = EnumField("Draw Mode", settings.drawMode);
        }

        private void DrawFieldSettings()
        {
            Header("Field Settings");

            settings.FieldResolution = FloatField("Field Resolution", settings.FieldResolution);
            settings.KernelResolution = FloatField("Kernel Resolution", settings.KernelResolution);
            settings.KernelSize = Vector2IntField("Kernel Size", settings.KernelSize);
        }

        private void DrawArrowSettings()
        {
            Header("Arrow Settings");

            settings.arrowSize = FloatField("Arrow Size", settings.arrowSize);
        }

        private static void Header(string text)
        {
            GUILayout.Space(8);
            GUILayout.Label($"<b>{text}</b>", RichLabel());
        }

        private static bool Toggle(string label, bool value)
        {
            return GUILayout.Toggle(value, label);
        }

        private int IntField(string label, int value)
        {
            GUILayout.BeginHorizontal();
            GUILayout.Label(label, GUILayout.Width(130));

            value = DelayedIntTextField(label, value);

            GUILayout.EndHorizontal();
            return value;
        }

        private float FloatField(string label, float value)
        {
            GUILayout.BeginHorizontal();
            GUILayout.Label(label, GUILayout.Width(130));

            value = DelayedFloatTextField(label, value);

            GUILayout.EndHorizontal();
            return value;
        }

        private Vector2Int Vector2IntField(string label, Vector2Int value)
        {
            GUILayout.BeginHorizontal();
            GUILayout.Label(label, GUILayout.Width(130));

            value.x = DelayedIntTextField(label + ".x", value.x, GUILayout.Width(70));
            value.y = DelayedIntTextField(label + ".y", value.y, GUILayout.Width(70));

            GUILayout.EndHorizontal();
            return value;
        }

        private int DelayedIntTextField(string key, int value, params GUILayoutOption[] options)
        {
            string text = DelayedTextField(key, value.ToString(CultureInfo.InvariantCulture), options);

            if (ShouldCommit(key) &&
                int.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out int result))
            {
                value = result;
                textBuffers[key] = value.ToString(CultureInfo.InvariantCulture);
            }

            return value;
        }

        private float DelayedFloatTextField(string key, float value, params GUILayoutOption[] options)
        {
            string text = DelayedTextField(key, value.ToString(CultureInfo.InvariantCulture), options);

            if (ShouldCommit(key) &&
                float.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out float result))
            {
                value = result;
                textBuffers[key] = value.ToString(CultureInfo.InvariantCulture);
            }

            return value;
        }

        private string DelayedTextField(string key, string currentValue, params GUILayoutOption[] options)
        {
            bool isFocused = GUI.GetNameOfFocusedControl() == key;

            if (!textBuffers.ContainsKey(key) || !isFocused && !focusedLastFrame.Contains(key))
                textBuffers[key] = currentValue;

            GUI.SetNextControlName(key);
            textBuffers[key] = GUILayout.TextField(textBuffers[key], options);

            return textBuffers[key];
        }

        private bool ShouldCommit(string key)
        {
            bool isFocused = GUI.GetNameOfFocusedControl() == key;
            bool wasFocused = focusedLastFrame.Contains(key);

            bool enterPressed =
                isFocused &&
                Event.current.type == EventType.KeyDown &&
                (Event.current.keyCode == KeyCode.Return ||
                 Event.current.keyCode == KeyCode.KeypadEnter);

            bool lostFocus = wasFocused && !isFocused;

            if (enterPressed)
            {
                GUI.FocusControl("");
                Event.current.Use();
            }

            if (isFocused)
                focusedLastFrame.Add(key);
            else
                focusedLastFrame.Remove(key);

            return lostFocus || enterPressed;
        }

        private static Settings.DrawMode EnumField(string label, Settings.DrawMode value)
        {
            GUILayout.Label(label);

            string[] names = Enum.GetNames(typeof(Settings.DrawMode));
            int selected = GUILayout.SelectionGrid((int)value, names, 1);

            return (Settings.DrawMode)selected;
        }

        private static GUIStyle RichLabel()
        {
            return new GUIStyle(GUI.skin.label)
            {
                richText = true
            };
        }
    }
}
